# Taking on -> https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

[build-system]

requires = ["setuptools >= 62.0.0"]

[project]
authors = [{name = "Alvaro Monllor", email = "alvarodrumer54@gmail.com"}]
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3.10",
  "Natural Language :: Spanish",
  "Typing :: Typed",
]
dependencies = [
    "colorama>=0.4.4", 
    "psutil>=5.9.0", "", 
    "chardet>=4.0.0",
    "typing_extensions>=3.7.4",
]
description = "Miscellaneous tools for Python"
keywords = [
  "Python",
  "Python-tools",
  "Miscellaneous tools"
]
license = {file = "LICENSE"}
name = "misctools"
readme = "README.md"
requires-python = ">=3.10.2"
version = "0.1.0"

[project.urls]
homepage = "https://github.com/Backist"
repository = "https://github.com/Backist/Misctools"

[tool.setuptools]
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
include = ["plane*"]

[tool.mypy]
python_version = "3.10.2"
strict = true

[tool.black]
lineLength = 88

[tool.isort]
profile = "black"
